import type { Metadata } from "next";
import {Outfit} from "next/font/google";
import "./globals.css";
import Provider from "./themeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const font=Outfit({subsets:['latin']})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={font.className} 
      >
        <Provider>
        {children}
        </Provider>
      </body>
    </html>
  );
}
